title: Hardware Repairs
description: Pages describing some repairs I've done
repository: rcowsill/HWRepairs
remote_theme: pages-themes/slate@v0.2.0
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "**/LICENSE"
  - "**/*.asm"
  - "**/*.c"
  - "**/*.cmd"
  - "**/*.h"


