title: Hardware Repairs
description: Pages describing some repairs I've done
repository: rcowsill/HWRepairs
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
